jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Comment
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
          JIRA_BASE_URL: https://dhingra-arjun.atlassian.net
          JIRA_USER_EMAIL: arjundhingra29@gmail.com
          JIRA_API_TOKEN: 
    - name: Jira Add Comment
      # You may pin to the exact commit or the version.
      # uses: atlassian/gajira-comment@8ec356b5df49f1325653db7ee2da2b59a1d78203
      uses: atlassian/gajira-comment@v2.0.2
      with:
        # Key of the issue to be commented on
        issue: TEST-6
        # Comment
        comment:   comment via github
