on:
  push

name: Test comment

jobs:
  test-comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: ArjunDhingra/connect-four-dots@master
      env:
        JIRA_BASE_URL: dhingra-arjun.atlassian.net
        JIRA_USER_EMAIL: arjundhingra29@gmail.com
        JIRA_API_TOKEN: i8eZBIteRJjokcriiAhAF435

    - name: Create new issue
      id: create
      uses: ArjunDhingra/connect-four-dots@master
      with:
        project: GA
        issuetype: Build
        summary: |
          Issue for comment ${{ github.repository }}
        description: |
          Compare branch|${{ github.event.compare }} # https://developer.github.com/v3/activity/events/types/#webhook-payload-example-31
    - name: Comment on issue
      uses: ./
      with:
        issue: ${{ steps.create.outputs.issue }}
        comment: Test comment ${{ github.event.compare }}
